### ISSUE TITLE
verify SALT in delegating password

### ISSUE THREAD

**Issue by Enrico-git** [Enrico-git/WA2-EGLR#15]

**Comment by thepassenger-hub** [comment]
BCrypt generates automatically a random salt every time the encoder is called and uses it to hash the password, therefore we don't need to add it ourselves.

Example: Hashed password is :

$2a$10$ZLhnHxdpHETcxmtEStgpI./Ri1mksgJ9iDP36FmfMdYyVg9g0b2dq

There are three fields separated by $:

The “2a” represents the BCrypt algorithm version
The “10” represents the strength of the algorithm
The “ZLhnHxdpHETcxmtEStgpI.” part is actually the randomly generated salt. Basically, the first 22 characters are salt. The remaining part of the last field is the actual hashed version of the plain text

https://www.baeldung.com/spring-security-registration-password-encoding-bcrypt
